//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class calls
    {
        public int Id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> manager { get; set; }
        public Nullable<int> cutomer { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> date_delivery { get; set; }
        public string delivery_from { get; set; }
        public string delivery_to { get; set; }
        public Nullable<System.TimeSpan> delivery_time_from { get; set; }
        public Nullable<System.TimeSpan> delivery_time_to { get; set; }
    
        public virtual status status1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
